--- 
- 
  copy: "src=.bash_aliases dest=\"/home/pi/.bash_aliases\""
  name: "Copy aliases"
  tags: aliases
- 
  name: "Set baudrate to 115200 for both serial-usb interfaces"
  shell: 
    cmd: "sudo stty -F /dev/ttyUSB0 115200; sudo stty -F /dev/ttyUSB1 115200;"
  tags: "console, log"
- 
  name: "Start writing serial log for USB0"
  shell: 
    cmd: "sudo cat /dev/ttyUSB0 | tee /var/log/console/usb0.log"
  tags: "console, log"
- 
  name: "Start writing serial log for USB1"
  shell: 
    cmd: "sudo cat /dev/ttyUSB1 | tee /var/log/console/usb1.log"
  tags: "console, log"
- 
  name: "Kill conflicting pids"
  shell: 
    cmd: "sudo airmon-ng check kill"
  tags: "wifi, log"
- 
  name: "Put wlxec086b1ed2c8 in monitor mode"
  shell: 
    cmd: "sudo airmon-ng wlxec086b1ed2c8 start"
  tags: "wifi, log"
- 
  name: "Start capturing 2.4 Ghz data"
  shell: 
    cmd: "airodump-ng -w /var/log/wifi --output-format pcap wlan1mon > /dev/null"
  tags: "wifi, log"
